export const GET_US_CHART_DATA = 'GET_US_CHART_DATA';
export const GET_US_DEFAULT_DATA = 'GET_US_DEFAULT_DATA';
export const GET_STATES_TABLE_DATA = 'GET_STATES_TABLE_DATA';
export const GET_STATES_CHART_DATA = 'GET_STATES_CHART_DATA';
export const FETCH_OV_DATA = 'FETCH_OV_DATA';
export const FETCH_US_DATA = 'FETCH_US_DATA';
export const FETCH_STOV_DATA = 'FETCH_STOV_DATA';
export const FETCH_STATES_DATA = 'FETCH_STATES_DATA';
